// ----------------------------------------------------------------------------------------
//                              COPYRIGHT NOTICE
// ----------------------------------------------------------------------------------------
//
// The Source Code Store LLC
// ACTIVEGANTT SCHEDULER COMPONENT FOR C# - ActiveGanttCSW
// WPF Control
// Copyright (c) 2002-2017 The Source Code Store LLC
//
// All Rights Reserved. No parts of this file may be reproduced, modified or transmitted 
// in any form or by any means without the written permission of the author.
//
// ----------------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Reflection;

namespace AGCSW
{

    internal static class Globals
    {

        static internal bool g_IsNumeric(string Expression)
        {
            double dDummy = 0;
            return double.TryParse(Expression, out dDummy);
        }

        internal static string g_Trim(string Expression)
        {
            return Expression.Trim();
        }

        internal static string g_Replace(string Expression, string sFind, string sReplace)
        {
            return Expression.Replace(sFind, sReplace);
        }

        internal static string g_GetDecimalSeparator()
        {
            return System.Globalization.NumberFormatInfo.CurrentInfo.NumberDecimalSeparator;
        }
    }

    internal struct S_Rectangle
    {
        internal int X1;
        internal int Y1;
        internal int X2;

        internal int Y2;
        internal bool mp_bInRect(int X, int Y)
        {
            if (X >= X1 & X <= X2 & Y >= Y1 & Y <= Y2)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

    }

    internal struct S_Point
    {
        internal int X;
        internal int Y;
    }

    internal struct S_TIMEBLOCK
    {
        public DateTime dtStart;
        public DateTime dtEnd;
    }

	internal enum E_CURSORTYPE
	{
		CT_NORMAL = 0,
		CT_SIZETASK = 1,
		CT_MOVETASK = 2,
		CT_MOVEMILESTONE = 3,
		CT_CLIENTAREA = 4,
		CT_MOVESPLITTER = 5,
		CT_ROWHEIGHT = 6,
		CT_COLUMNWIDTH = 7,
		CT_MOVEROW = 8,
		CT_MOVECOLUMN = 11,
		CT_SCROLLTIMELINE = 9,
		CT_NODROP = 10,
		CT_PERCENTAGE = 12,
		CT_PREDECESSOR = 13,
        CT_IBEAM = 14
	}

	internal enum E_MOUSEKEYBOARDEVENTS
	{
		MouseHover = 0,
		MouseDown = 1,
		MouseMove = 2,
		MouseUp = 3,
		MouseClick = 4,
		MouseDblClick = 5,
		MouseWheel = 6,
		KeyPress = 7,
		KeyDown = 8,
		KeyUp = 9
	}

	internal enum E_CLIENTAREAVISIBILITY
	{
		VS_ABOVEVISIBLEAREA = 0,
		VS_INSIDEVISIBLEAREA = 1,
		VS_BELOWVISIBLEAREA = 2,
        VS_LEFTOFVISIBLEAREA = 3,
        VS_RIGHTOFVISIBLEAREA = 4,
	}

    public enum GRE_DRAWINGOBJECT
    {
        DO_GENERAL = 0,
        DO_MILESTONE = 1
    }

    public enum GRE_PAPERTYPE
    {
        PK_CUSTOM = 0,
        PK_LETTER = 1,
        PK_LETTERSMALL = 2,
        PK_TABLOID = 3,
        PK_LEDGER = 4,
        PK_LEGAL = 5,
        PK_STATEMENT = 6,
        PK_EXECUTIVE = 7,
        PK_A3 = 8,
        PK_A4 = 9,
        PK_A4SMALL = 10,
        PK_A5 = 11,
        PK_B4 = 12,
        PK_B5 = 13,
        PK_FOLIO = 14,
        PK_QUARTO = 15,
        PK_STANDARD10X14 = 16,
        PK_STANDARD11X17 = 17,
        PK_NOTE = 18,
        PK_NUMBER9ENVELOPE = 19,
        PK_NUMBER10ENVELOPE = 20,
        PK_NUMBER11ENVELOPE = 21,
        PK_NUMBER12ENVELOPE = 22,
        PK_NUMBER14ENVELOPE = 23,
        PK_CSHEET = 24,
        PK_DSHEET = 25,
        PK_ESHEET = 26,
        PK_DLENVELOPE = 27,
        PK_C5ENVELOPE = 28,
        PK_C3ENVELOPE = 29,
        PK_C4ENVELOPE = 30,
        PK_C6ENVELOPE = 31,
        PK_C65ENVELOPE = 32,
        PK_B4ENVELOPE = 33,
        PK_B5ENVELOPE = 34,
        PK_B6ENVELOPE = 35,
        PK_ITALYENVELOPE = 36,
        PK_MONARCHENVELOPE = 37,
        PK_PERSONALENVELOPE = 38,
        PK_USSTANDARDFANFOLD = 39,
        PK_GERMANSTANDARDFANFOLD = 40,
        PK_GERMANLEGALFANFOLD = 41,
        PK_ISOB4 = 42,
        PK_JAPANESEPOSTCARD = 43,
        PK_STANDARD9X11 = 44,
        PK_STANDARD10X11 = 45,
        PK_STANDARD15X11 = 46,
        PK_INVITEENVELOPE = 47,
        PK_48 = 48,
        PK_49 = 49,
        PK_LETTEREXTRA = 50,
        PK_LEGALEXTRA = 51,
        PK_TABLOIDEXTRA = 52,
        PK_A4EXTRA = 53,
        PK_LETTERTRANSVERSE = 54,
        PK_A4TRANSVERSE = 55,
        PK_LETTEREXTRATRANSVERSE = 56,
        PK_APLUS = 57,
        PK_BPLUS = 58,
        PK_LETTERPLUS = 59,
        PK_A4PLUS = 60,
        PK_A5TRANSVERSE = 61,
        PK_B5TRANSVERSE = 62,
        PK_A3EXTRA = 63,
        PK_A5EXTRA = 64,
        PK_B5EXTRA = 65,
        PK_A2 = 66,
        PK_A3TRANSVERSE = 67,
        PK_A3EXTRATRANSVERSE = 68,
        PK_JAPANESEDOUBLEPOSTCARD = 69,
        PK_A6 = 70,
        PK_JAPANESEENVELOPEKAKUNUMBER2 = 71,
        PK_JAPANESEENVELOPEKAKUNUMBER3 = 72,
        PK_JAPANESEENVELOPECHOUNUMBER3 = 73,
        PK_JAPANESEENVELOPECHOUNUMBER4 = 74,
        PK_LETTERROTATED = 75,
        PK_A3ROTATED = 76,
        PK_A4ROTATED = 77,
        PK_A5ROTATED = 78,
        PK_B4JISROTATED = 79,
        PK_B5JISROTATED = 80,
        PK_JAPANESEPOSTCARDROTATED = 81,
        PK_JAPANESEDOUBLEPOSTCARDROTATED = 82,
        PK_A6ROTATED = 83,
        PK_JAPANESEENVELOPEKAKUNUMBER2ROTATED = 84,
        PK_JAPANESEENVELOPEKAKUNUMBER3ROTATED = 85,
        PK_JAPANESEENVELOPECHOUNUMBER3ROTATED = 86,
        PK_JAPANESEENVELOPECHOUNUMBER4ROTATED = 87,
        PK_B6JIS = 88,
        PK_B6JISROTATED = 89,
        PK_STANDARD12X11 = 90,
        PK_JAPANESEENVELOPEYOUNUMBER4 = 91,
        PK_JAPANESEENVELOPEYOUNUMBER4ROTATED = 92,
        PK_PRC16K = 93,
        PK_PRC32K = 94,
        PK_PRC32KBIG = 95,
        PK_PRCENVELOPENUMBER1 = 96,
        PK_PRCENVELOPENUMBER2 = 97,
        PK_PRCENVELOPENUMBER3 = 98,
        PK_PRCENVELOPENUMBER4 = 99,
        PK_PRCENVELOPENUMBER5 = 100,
        PK_PRCENVELOPENUMBER6 = 101,
        PK_PRCENVELOPENUMBER7 = 102,
        PK_PRCENVELOPENUMBER8 = 103,
        PK_PRCENVELOPENUMBER9 = 104,
        PK_PRCENVELOPENUMBER10 = 105,
        PK_PRC16KROTATED = 106,
        PK_PRC32KROTATED = 107,
        PK_PRC32KBIGROTATED = 108,
        PK_PRCENVELOPENUMBER1ROTATED = 109,
        PK_PRCENVELOPENUMBER2ROTATED = 110,
        PK_PRCENVELOPENUMBER3ROTATED = 111,
        PK_PRCENVELOPENUMBER4ROTATED = 112,
        PK_PRCENVELOPENUMBER5ROTATED = 113,
        PK_PRCENVELOPENUMBER6ROTATED = 114,
        PK_PRCENVELOPENUMBER7ROTATED = 115,
        PK_PRCENVELOPENUMBER8ROTATED = 116,
        PK_PRCENVELOPENUMBER9ROTATED = 117,
        PK_PRCENVELOPENUMBER10ROTATED = 118
    }

    public enum GRE_ORIENTATION
    {
        OT_PORTRAIT = 0,
        OT_LANDSCAPE = 1
    }

    public enum GRE_PRINTERRESOLUTION
    {
        PR_HIGH = 0,
        PR_MEDIUM = 1,
        PR_LOW = 2,
        PR_DRAFT = 3,
        PR_CUSTOM = 4
    }

	public enum GRE_ARROWDIRECTION
	{
		AWD_UP = 0,
		AWD_DOWN = 1,
		AWD_LEFT = 2,
		AWD_RIGHT = 3
	}

	public enum GRE_LINEDRAWSTYLE
	{
		LDS_SOLID = 0,
		LDS_DASH = 1,
		LDS_DOT = 2,
		LDS_DASHDOT = 3,
		LDS_DASHDOTDOT = 4
	}

	public enum GRE_EDGETYPE
	{
		ET_SUNKEN = 1,
		ET_RAISED = 2
	}

	public enum GRE_BUTTONSTYLE
	{
		BT_NORMALWINDOWS = 0,
		BT_LIGHTWEIGHT = 1
	}

	public enum GRE_LINETYPE
	{
		LT_NORMAL = 0,
		LT_BORDER = 1,
		LT_FILLED = 2
	}

	public enum GRE_BACKGROUNDMODE
	{
		FP_SOLID = 0,
		FP_TRANSPARENT = 1,
		FP_GRADIENT = 2,
		FP_PATTERN = 3,
		FP_HATCH = 4
	}

	public enum GRE_PATTERN
	{
		FP_HORIZONTALLINE = 2,
		FP_VERTICALLINE = 3,
		FP_UPWARDDIAGONAL = 4,
		FP_DOWNWARDDIAGONAL = 5,
		FP_CROSS = 6,
		FP_DIAGONALCROSS = 7,
		FP_LIGHT = 8,
		FP_MEDIUM = 9,
		FP_DARK = 10
	}

	public enum GRE_HATCHSTYLE
	{
		HS_HORIZONTAL = 0,
		HS_VERTICAL = 1,
		HS_FORWARDDIAGONAL = 2,
		HS_BACKWARDDIAGONAL = 3,
		HS_LARGEGRID = 4,
		HS_DIAGONALCROSS = 5,
		HS_PERCENT05 = 6,
		HS_PERCENT10 = 7,
		HS_PERCENT20 = 8,
		HS_PERCENT25 = 9,
		HS_PERCENT30 = 10,
		HS_PERCENT40 = 11,
		HS_PERCENT50 = 12,
		HS_PERCENT60 = 13,
		HS_PERCENT70 = 14,
		HS_PERCENT75 = 15,
		HS_PERCENT80 = 16,
		HS_PERCENT90 = 17,
		HS_LIGHTDOWNWARDDIAGONAL = 18,
		HS_LIGHTUPWARDDIAGONAL = 19,
		HS_DARKDOWNWARDDIAGONAL = 20,
		HS_DARKUPWARDDIAGONAL = 21,
		HS_WIDEDOWNWARDDIAGONAL = 22,
		HS_WIDEUPWARDDIAGONAL = 23,
		HS_LIGHTVERTICAL = 24,
		HS_LIGHTHORIZONTAL = 25,
		HS_NARROWVERTICAL = 26,
		HS_NARROWHORIZONTAL = 27,
		HS_DARKVERTICAL = 28,
		HS_DARKHORIZONTAL = 29,
		HS_DASHEDDOWNWARDDIAGONAL = 30,
		HS_DASHEDUPWARDDIAGONAL = 31,
		HS_DASHEDHORIZONTAL = 32,
		HS_DASHEDVERTICAL = 33,
		HS_SMALLCONFETTI = 34,
		HS_LARGECONFETTI = 35,
		HS_ZIGZAG = 36,
		HS_WAVE = 37,
		HS_DIAGONALBRICK = 38,
		HS_HORIZONTALBRICK = 39,
		HS_WEAVE = 40,
		HS_PLAID = 41,
		HS_DIVOT = 42,
		HS_DOTTEDGRID = 43,
		HS_DOTTEDDIAMOND = 44,
		HS_SHINGLE = 45,
		HS_TRELLIS = 46,
		HS_SPHERE = 47,
		HS_SMALLGRID = 48,
		HS_SMALLCHECKERBOARD = 49,
		HS_LARGECHECKERBOARD = 50,
		HS_OUTLINEDDIAMOND = 51,
		HS_SOLIDDIAMOND = 52
	}

	public enum GRE_FIGURETYPE
	{
		FT_NONE = 0,
		FT_PROJECTUP = 1,
		FT_PROJECTDOWN = 2,
		FT_DIAMOND = 3,
		FT_CIRCLEDIAMOND = 4,
		FT_TRIANGLEUP = 5,
		FT_TRIANGLEDOWN = 6,
		FT_TRIANGLERIGHT = 7,
		FT_TRIANGLELEFT = 8,
		FT_CIRCLETRIANGLEUP = 9,
		FT_CIRCLETRIANGLEDOWN = 10,
		FT_ARROWUP = 11,
		FT_ARROWDOWN = 12,
		FT_CIRCLEARROWUP = 13,
		FT_CIRCLEARROWDOWN = 14,
		FT_SMALLPROJECTUP = 15,
		FT_SMALLPROJECTDOWN = 16,
		FT_RECTANGLE = 17,
		FT_SQUARE = 18,
		FT_CIRCLE = 19
	}

	public enum GRE_VERTICALALIGNMENT
	{
		VAL_TOP = 1,
		VAL_CENTER = 2,
		VAL_BOTTOM = 3
	}

	public enum GRE_HORIZONTALALIGNMENT
	{
		HAL_LEFT = 1,
		HAL_CENTER = 2,
		HAL_RIGHT = 3
	}

	public enum GRE_GRADIENTFILLMODE
	{
		GDT_HORIZONTAL = 0,
		GDT_VERTICAL = 1
	}

	public enum GRE_FILLMODE
	{
		FM_COMPLETELYFILLED = 0,
		FM_UPPERHALFFILLED = 1,
		FM_LOWERHALFFILLED = 2
	}

	public enum E_EVENTTARGET
	{
		EVT_NONE = 0,
		EVT_TASK = 1,
		EVT_PERCENTAGE = 2,
		EVT_MILESTONE = 3,
		EVT_ROW = 4,
		EVT_CELL = 5,
		EVT_COLUMN = 6,
		EVT_CLIENTAREA = 7,
		EVT_EMPTYAREA = 8,
		EVT_GRID = 9,
		EVT_TIMELINE = 10,
		EVT_TIMEBLOCK = 11,
		EVT_HSCROLLBAR = 12,
		EVT_TIMELINESCROLLBAR = 13,
		EVT_VSCROLLBAR = 14,
		EVT_TREEVIEW = 15,
		EVT_SPLITTER = 16,
		EVT_NODE = 17,
		EVT_TREEVIEWCHECKBOX = 19,
		EVT_TREEVIEWSIGN = 20,
		EVT_SELECTEDCOLUMN = 50,
		EVT_SELECTEDROW = 51,
		EVT_SELECTEDTASK = 52,
		EVT_SELECTEDPERCENTAGE = 54,
		EVT_PREDECESSOR = 56,
        EVT_SELECTEDPREDECESSOR = 57
	}

	public enum E_OPERATION
	{
		EO_NONE = 0,
    
		EO_TASKADDITION = 1,
		EO_TASKMOVEMENT = 2,
		EO_TASKSTRETCHLEFT = 3,
		EO_TASKSTRETCHRIGHT = 4,
		EO_TASKSELECTION = 5,
    
		EO_MILESTONEADDITION = 6,
    
		EO_ROWSIZING = 9,
		EO_ROWMOVEMENT = 10,
		EO_ROWSELECTION = 11,
    
		EO_COLUMNSIZING = 12,
		EO_COLUMNMOVEMENT = 13,
		EO_COLUMNSELECTION = 14,
    
		EO_TIMELINEMOVEMENT = 16,
    
		EO_SPLITTERMOVEMENT = 18,
    
		EO_HORIZONTALSCROLLBAR = 19,
		EO_VERTICALSCROLLBAR = 20,
		EO_TIMELINESCROLLBAR = 21,
		EO_TREEVIEW = 22,
    
		EO_PERCENTAGESELECTION = 23,
		EO_PERCENTAGESIZING = 24,
    
		////Treeview
		EO_CHECKBOXCLICK = 27,
		EO_SIGNCLICK = 28,
    
		////Predecessors
		EO_PREDECESSORADDITION = 29,
        EO_PREDECESSORSELECTION = 30
    
	}

	public enum E_TIERPOSITION
	{
		SP_UPPER = 0,
		SP_LOWER = 1,
		SP_MIDDLE = 2
	}

	public enum E_SORTTYPE
	{
		ES_STRING = 0,
		ES_NUMERIC = 1,
		ES_DATE = 2
	}

	public enum E_ADDMODE
	{
		AT_TASKADD = 0,
		AT_MILESTONEADD = 1,
		AT_BOTH = 2,
        AT_DURATION_TASKADD = 3,
        AT_DURATION_MILESTONEADD = 4,
        AT_DURATION_BOTH = 5
	}

	public enum E_OBJECTTYPE
	{
		OT_TASK = 0,
		OT_MILESTONE = 1
	}

	public enum E_PLACEMENT
	{
		PLC_ROWEXTENTSPLACEMENT = 0,
		PLC_OFFSETPLACEMENT = 1
	}

	public enum E_TEXTPLACEMENT
	{
		SCP_OBJECTEXTENTSPLACEMENT = 0,
		SCP_OFFSETPLACEMENT = 1,
		SCP_EXTERIORPLACEMENT = 2
	}

	public enum E_STYLEAPPEARANCE
	{
		SA_RAISED = 0,
		SA_SUNKEN = 1,
		SA_FLAT = 2,
		SA_GRAPHICAL = 3
	}

	public enum E_SCROLLBEHAVIOUR
	{
		SB_DISABLE = 0,
		SB_HIDE = 1
	}

	public enum E_REPORTERRORS
	{
		RE_MSGBOX = 0,
		RE_RAISE = 1,
		RE_RAISEEVENT = 2,
		RE_HIDE = 3
	}

    public enum E_PROGRESSLINELENGTH
    {
        TLMA_TICKMARKAREA = 0,
        TLMA_CLIENTAREA = 1,
        TLMA_TIMELINE = 2,
        TLMA_CA_TIMELINE = 3,
        TLMA_CA_TICKMARKAREA = 4,
        TLMA_NONE = 5
    }

	public enum GRE_BORDERSTYLE
	{
		SBR_NONE = 0,
		SBR_SINGLE = 1,
		SBR_CUSTOM = 2
	}

	public enum E_BORDERSTYLE
	{
		TLB_NONE = 0,
		TLB_SINGLE = 1,
		TLB_3D = 2
	}

	public enum E_TIERTYPE
	{
        ST_NOT_VISIBLE = 0,
		ST_DAYOFWEEK = 1,
		ST_MONTH = 2,
		ST_QUARTER = 3,
		ST_YEAR = 4,
		ST_WEEK = 5,
		ST_CUSTOM = 6,
		ST_DAY = 7,
		ST_DAYOFYEAR = 8,
		ST_HOUR = 9,
		ST_MINUTE = 10,
        ST_SECOND = 11,
        ST_MILLISECOND = 12,
        ST_MICROSECOND = 13
	}

	public enum E_PROGRESSLINETYPE
	{
		TLMT_SYSTEMTIME = 0,
		TLMT_USER = 1
	}

	public enum E_TIMEBLOCKBEHAVIOUR
	{
		TBB_ROWEXTENTS = 0,
		TBB_CONTROLEXTENTS = 1
	}

	public enum E_LAYEROBJECTENABLE
	{
		EC_INCURRENTLAYERONLY = 0,
		EC_INALLLAYERS = 1
	}

	public enum E_MOVEMENTTYPE
	{
		MT_UNRESTRICTED = 0,
		MT_RESTRICTEDTOROW = 1,
		MT_MOVEMENTDISABLED = 2
	}

	public enum E_TICKMARKTYPES
	{
		TLT_BIG = 0,
		TLT_MEDIUM = 1,
		TLT_SMALL = 2
	}

	public enum E_SCROLLBAR
	{
		SCR_VERTICAL = 0,
		SCR_HORIZONTAL1 = 1,
		SCR_HORIZONTAL2 = 2
	}

	public enum E_CONTROLMODE
	{
		CM_GRID = 0,
		CM_TREEVIEW = 1
	}

	public enum E_CONSTRAINTTYPE
	{
		PCT_END_TO_START = 0,
		PCT_START_TO_START = 1,
		PCT_END_TO_END = 2,
		PCT_START_TO_END = 3
	}

	public enum E_TIMEBLOCKTYPE
	{
		TBT_SINGLE_OCURRENCE = 0,
		TBT_RECURRING = 1
	}

	public enum E_RECURRINGTYPE
	{
        RCT_DAY = 3,
        RCT_WEEK = 4,
        RCT_MONTH = 5,
        RCT_YEAR = 7
	}

    public enum E_WEEKDAY
    {
        WD_SUNDAY = 0,
        WD_MONDAY = 1,
        WD_TUESDAY = 2,
        WD_WEDNESDAY = 3,
        WD_THURSDAY = 4,
        WD_FRIDAY = 5,
        WD_SATURDAY = 6
    }

    public enum E_CALENDARWEEKRULES
    {
        CWR_FIRSTDAY = 0,
        CWR_FIRSTFULLWEEK = 1,
        CWR_FIRSTFOURDAYWEEK = 2
    }

	public enum E_TOOLTIPTYPE
	{
		TPT_HOVER = 0,
		TPT_MOVEMENT = 1
	}

	public enum E_MOUSEBUTTONS
	{
        BTN_NONE = -1,
        BTN_LEFT = 0,
        BTN_RIGHT = 2,
        BTN_MIDDLE = 1,
        BTN_XBUTTON1 = 3,
        BTN_XBUTTON2 = 4
	}

    public enum E_INTERVAL
    {
        IL_MILLISECOND = 2,
        IL_SECOND = 3,
        IL_MINUTE = 4,
        IL_HOUR = 5,
        IL_DAY = 6,
        IL_WEEK = 7,
        IL_MONTH = 8,
        IL_QUARTER = 9,
        IL_YEAR = 10
    }

    public enum E_SPLITTERTYPE
    {
        SA_APPEARANCE = 1,
        SA_USERDEFINED = 2,
        SA_STYLE = 3
    }

    public enum E_TIERBACKGROUNDMODE
    {
        ETBGM_TIERAPPEARANCE = 0,
        ETBGM_STYLE = 2
    }



    public enum E_SELECTIONRECTANGLEMODE
    {
        SRM_DOTTED = 0,
        SRM_COLOR = 1
    }

    public enum E_TEXTOBJECTTYPE
    {
        TOT_TASK = 1,
        TOT_ROW = 2,
        TOT_CELL = 3,
        TOT_COLUMN = 4,
        TOT_NODE = 5,
    }

    public enum E_PREDECESSORMODE
    {
        PM_FORCE = 0,
        PM_CREATEWARNINGFLAG = 1,
        PM_RAISEEVENT = 2
    }

    public enum E_TASKTYPE
    {
        TT_START_END = 0,
        TT_DURATION = 1,
        TT_UNITS_DURATION_WORK = 2
    }

    public enum E_TBINTERVALTYPE
    {
        TBIT_AUTOMATIC = 0,
        TBIT_MANUAL = 1
    }

    public enum E_PROGRESSLINESTYLE
    {
        PLT_STANDARD = 1,
        PLT_USERDEFINED = 2,
        PLT_STYLE = 3
    }

    public enum E_OBJECTSCOPE
    {
        OS_CONTROL = 0,
        OS_VIEW = 1
    }

    public enum E_OBJECTTEMPLATE
    {
        STO_NONE = 0,
        STO_BW_HATCH = 1,
        STO_COLOR_HATCH = 2,
        STO_GREY_SOLID = 3,
        STO_COLORS_SOLID = 4,
        STO_DEFAULT = 5,
        STO_VARIATION_1 = 6
    }

    public enum E_CONTROLTEMPLATE
    {
        STC_NONE = 0,
        STC_CH_SOLID_WHITE = 1,
        STC_CH_SOLID_DARK_BLUE = 2,
        STC_CH_SOLID_VIOLET = 3,
        STC_CH_SOLID_GREEN = 4,
        STC_CH_SOLID_RED = 5,
        STC_CH_SOLID_LIGHT_BLUE = 6,
        STC_CH_SOLID_GREY = 7,
        STC_CH_SOLID_LIGHT_STEEL_BLUE = 8,
        STC_CH_VGRAD_YELLOW = 9,
        STC_CH_VGRAD_ORANGE = 10,
        STC_CH_VGRAD_RED = 11,
        STC_CH_VGRAD_CRIMSON = 12,
        STC_CH_VGRAD_MAGENTA = 13,
        STC_CH_VGRAD_MULBERRY = 14,
        STC_CH_VGRAD_BLUE_VIOLET = 15,
        STC_CH_VGRAD_ANAKIWA_BLUE = 16,
        STC_CH_VGRAD_BLUE_BELL = 17,
        STC_CH_VGRAD_BLUE = 18,
        STC_CH_VGRAD_AERO = 19,
        STC_CH_HGRAD_YELLOW = 20,
        STC_CH_HGRAD_ORANGE = 21,
        STC_CH_HGRAD_RED = 22,
        STC_CH_HGRAD_CRIMSON = 23,
        STC_CH_HGRAD_MAGENTA = 24,
        STC_CH_HGRAD_MULBERRY = 25,
        STC_CH_HGRAD_BLUE_VIOLET = 26,
        STC_CH_HGRAD_ANAKIWA_BLUE = 27,
        STC_CH_HGRAD_BLUE_BELL = 28,
        STC_CH_HGRAD_BLUE = 29,
        STC_CH_HGRAD_AERO = 30
    }

    public enum E_TREEVIEWMODE
    {
        TM_NONE = 0,
        TM_PLUSMINUSSIGNS = 1,
        TM_EXPANDCOLLAPSEICONS = 2,
    }

    public enum E_CHANGETYPE
    {
        CT_MOVE = 0,
        CT_SIZE = 1
    }

	public enum SYS_ERRORS
	{
		ERR_RETARRELEMKEY_G = 51132,
		ERR_COLLREMWHERE_1_G = 51133,
		ERR_COLLREMWHERE_2_G = 51134,
		ERR_COLLREMWHERE_3_G = 51135,
		ERR_COLLREMWHERE_4_G = 51136,
		ERR_COLLREMWHERENOT_1_G = 51137,
		ERR_COLLREMWHERENOT_2_G = 51138,
		ERR_COLLREMWHERENOT_3_G = 51139,
		ERR_COLLREMWHERENOT_4_G = 51140,
		ERR_ADDMODE_G = 51141,
		TASKS_ITEM_1 = 51142,
		TASKS_ITEM_2 = 51143,
		TASKS_ITEM_3 = 51144,
		TASKS_ITEM_4 = 51145,
		TASKS_ADD_1 = 51146,
		TASKS_ADD_2 = 51147,
		TASKS_ADD_3 = 51148,
		TASKS_REMOVE_1 = 51149,
		TASKS_REMOVE_2 = 51150,
		TASKS_REMOVE_3 = 51151,
		TASKS_REMOVE_4 = 51152,
		TASKS_SET_KEY = 51153,
		ROWS_ITEM_1 = 51155,
		ROWS_ITEM_2 = 51156,
		ROWS_ITEM_3 = 51157,
		ROWS_ITEM_4 = 51158,
		ROWS_ADD_1 = 51159,
		ROWS_ADD_2 = 51160,
		ROWS_ADD_3 = 51161,
		ROWS_REMOVE_1 = 51162,
		ROWS_REMOVE_2 = 51163,
		ROWS_REMOVE_3 = 51164,
		ROWS_REMOVE_4 = 51165,
		ROWS_SET_KEY = 51166,
		COLUMNS_ITEM_1 = 51168,
		COLUMNS_ITEM_2 = 51169,
		COLUMNS_ITEM_3 = 51170,
		COLUMNS_ITEM_4 = 51171,
		COLUMNS_ADD_1 = 51172,
		COLUMNS_ADD_2 = 51173,
		COLUMNS_ADD_3 = 51174,
		COLUMNS_REMOVE_1 = 51175,
		COLUMNS_REMOVE_2 = 51176,
		COLUMNS_REMOVE_3 = 51177,
		COLUMNS_REMOVE_4 = 51178,
		COLUMNS_SET_KEY = 51179,
		CELLS_ITEM_1 = 51181,
		CELLS_ITEM_2 = 51182,
		CELLS_ITEM_3 = 51183,
		CELLS_ITEM_4 = 51184,
		CELLS_ADD_1 = 51185,
		CELLS_ADD_2 = 51186,
		CELLS_ADD_3 = 51187,
		CELLS_REMOVE_1 = 51188,
		CELLS_REMOVE_2 = 51189,
		CELLS_REMOVE_3 = 51190,
		CELLS_REMOVE_4 = 51191,
		CELLS_SET_KEY = 51192,
		PREDECESSORS_ITEM_1 = 51194,
		PREDECESSORS_ITEM_2 = 51195,
		PREDECESSORS_ITEM_3 = 51196,
		PREDECESSORS_ITEM_4 = 51197,
		PREDECESSORS_ADD_1 = 51198,
		PREDECESSORS_ADD_2 = 51199,
		PREDECESSORS_ADD_3 = 51200,
		PREDECESSORS_REMOVE_1 = 51201,
		PREDECESSORS_REMOVE_2 = 51202,
		PREDECESSORS_REMOVE_3 = 51203,
		PREDECESSORS_REMOVE_4 = 51204,
		PREDECESSORS_SET_KEY = 51205,
		TIMEBLOCKS_ITEM_1 = 51207,
		TIMEBLOCKS_ITEM_2 = 51208,
		TIMEBLOCKS_ITEM_3 = 51209,
		TIMEBLOCKS_ITEM_4 = 51210,
		TIMEBLOCKS_ADD_1 = 51211,
		TIMEBLOCKS_ADD_2 = 51212,
		TIMEBLOCKS_ADD_3 = 51213,
		TIMEBLOCKS_REMOVE_1 = 51214,
		TIMEBLOCKS_REMOVE_2 = 51215,
		TIMEBLOCKS_REMOVE_3 = 51216,
		TIMEBLOCKS_REMOVE_4 = 51217,
		TIMEBLOCKS_SET_KEY = 51218,
		LAYERS_ITEM_1 = 51220,
		LAYERS_ITEM_2 = 51221,
		LAYERS_ITEM_3 = 51222,
		LAYERS_ITEM_4 = 51223,
		LAYERS_ADD_1 = 51224,
		LAYERS_ADD_2 = 51225,
		LAYERS_ADD_3 = 51226,
		LAYERS_REMOVE_1 = 51227,
		LAYERS_REMOVE_2 = 51228,
		LAYERS_REMOVE_3 = 51229,
		LAYERS_REMOVE_4 = 51230,
		LAYERS_SET_KEY = 51231,
		STYLES_ITEM_1 = 51233,
		STYLES_ITEM_2 = 51234,
		STYLES_ITEM_3 = 51235,
		STYLES_ITEM_4 = 51236,
		STYLES_ADD_1 = 51237,
		STYLES_ADD_2 = 51238,
		STYLES_ADD_3 = 51239,
		STYLES_REMOVE_1 = 51240,
		STYLES_REMOVE_2 = 51241,
		STYLES_REMOVE_3 = 51242,
		STYLES_REMOVE_4 = 51243,
		STYLES_SET_KEY = 51244,
		PERCENTAGES_ITEM_1 = 51246,
		PERCENTAGES_ITEM_2 = 51247,
		PERCENTAGES_ITEM_3 = 51248,
		PERCENTAGES_ITEM_4 = 51249,
		PERCENTAGES_ADD_1 = 51250,
		PERCENTAGES_ADD_2 = 51251,
		PERCENTAGES_ADD_3 = 51252,
		PERCENTAGES_REMOVE_1 = 51253,
		PERCENTAGES_REMOVE_2 = 51254,
		PERCENTAGES_REMOVE_3 = 51255,
		PERCENTAGES_REMOVE_4 = 51256,
		PERCENTAGES_SET_KEY = 51257,
		VIEWS_ITEM_1 = 51272,
		VIEWS_ITEM_2 = 51273,
		VIEWS_ITEM_3 = 51274,
		VIEWS_ITEM_4 = 51275,
		VIEWS_ADD_1 = 51276,
		VIEWS_ADD_2 = 51277,
		VIEWS_ADD_3 = 51278,
		VIEWS_REMOVE_1 = 51279,
		VIEWS_REMOVE_2 = 51280,
		VIEWS_REMOVE_3 = 51281,
		VIEWS_REMOVE_4 = 51282,
		VIEWS_SET_KEY = 51283,
		TIERCOLORS_ITEM_1 = 51285,
		TIERCOLORS_ITEM_2 = 51286,
		TIERCOLORS_ITEM_3 = 51287,
		TIERCOLORS_ITEM_4 = 51288,
		TIERCOLORS_ADD_1 = 51289,
		TIERCOLORS_ADD_2 = 51290,
		TIERCOLORS_ADD_3 = 51291,
		TIERCOLORS_REMOVE_1 = 51292,
		TIERCOLORS_REMOVE_2 = 51293,
		TIERCOLORS_REMOVE_3 = 51294,
		TIERCOLORS_REMOVE_4 = 51295,
		TIERCOLORS_SET_KEY = 51296,
		TICKMARKS_ITEM_1 = 51298,
		TICKMARKS_ITEM_2 = 51299,
		TICKMARKS_ITEM_3 = 51300,
		TICKMARKS_ITEM_4 = 51301,
		TICKMARKS_ADD_1 = 51302,
		TICKMARKS_ADD_2 = 51303,
		TICKMARKS_ADD_3 = 51304,
		TICKMARKS_REMOVE_1 = 51305,
		TICKMARKS_REMOVE_2 = 51306,
		TICKMARKS_REMOVE_3 = 51307,
		TICKMARKS_REMOVE_4 = 51308,
		TICKMARKS_SET_KEY = 51309,
		INVALID_INTERVAL = 51310,
		INVALID_LAYER_INDEX = 51311,
		GETINDEXANDKEY_ITEM1 = 51312,
		GETINDEXANDKEY_ITEM2 = 51313,
		GETINDEXANDKEY_ITEM3 = 51314,
		GETINDEXANDKEY_ITEM4 = 51315,
		INVALID_ROW_KEY = 51316,
		STYLE_INVALID_INDEX = 51317,
		STYLE_INVALID_KEY = 51318,
        MP_REMOVE_1 = 51596,
        MP_REMOVE_2 = 51597,
        MP_REMOVE_3 = 51598,
        MP_REMOVE_4 = 51599,
        MP_ITEM_1 = 51600,
        MP_ITEM_2 = 51601,
        MP_ITEM_3 = 51602,
        MP_ITEM_4 = 51603,
        MP_ADD_1 = 51604,
        MP_ADD_2 = 51605,
        MP_ADD_3 = 51606,
        MP_SET_KEY = 51607,
        SPLITTER_INVALIDOP = 51608,
        SPLITTER_INVALID_INDEX = 51609,
        SPLITTER_INVALID_WIDTH = 51610,
        STYLE_NULL = 51611,
        INVALID_DURATION_INTERVAL = 51612,
        CHECK_DURATION_ERROR = 51613,
        ERR_DURATION_INCONSISTENT = 51614,
        PROGRESSLINE_INVALIDOP = 51615,
        PROGRESSLINE_INVALID_INDEX = 51616,
        PROGRESSLINE_INVALID_WIDTH = 51617,
        PRINTER_INVALID_DATE_RANGE = 51618,
        PRINTER_NO_ROWS = 51619,
        PRINTER_INVALID_ROW_RANGE = 51620,
        PRINTER_INVALID_COLUMN = 51621,
        PRINTER_INVALID_ROW = 51622,
        PRINTER_INVALID_PAGE = 51623,
        PRINTER_INVALID_PAGE_RANGE = 51624,
        PRINTER_INVALID_SCALE = 51625,
        PRINTER_INVALID_SPECS_MARGINS = 51626,
        PRINTER_INVALID_SPECS_HEIGHT = 51627,
        PRINTER_INVALID_SPECS_COLUMNSINEVERYPAGE = 51628,
        PRINTER_INVALID_SPECS_COLUMNS = 51629,
        PRINTER_INVALID_SPECS_INTERVAL = 51630,
        OBJECT_COUNT_ERROR = 51631,
        ERR_RETARRELEMINDEX_G = 51632,
        NODE_INVALID_DEPTH = 51633,
        ROWS_INVALID_TREE_STRUCTURE = 51634,
	}

	internal enum E_SCROLLSTATE
	{
		SS_CANTDISPLAY = 0,
		SS_NOTNEEDED = 1,
		SS_NEEDED = 2,
		SS_SHOWN = 3,
		SS_HIDDEN = 4
	}

	internal enum E_AREA
	{
		EA_NONE = 0,
		EA_LEFT = 1,
		EA_TOP = 2,
		EA_RIGHT = 3,
		EA_BOTTOM = 4,
		EA_CENTER = 5
	}

	internal enum E_FOCUSTYPE
	{
		FCT_NORMAL = 0,
		FCT_KEEPLEFTRIGHTBOUNDS = 1,
		FCT_ADD = 2,
		FCT_VERTICALSPLITTER = 3
	}

}